feat: 适配天数
YdrMaster/operators-rs pull request #7
Opened 2024-12-31 00:18 UTC by onenewcode

2024-12-31 02:55 UTC, YdrMaster commented
我想了一下，cfg flag 应该把原来的 use_cuda 改成 use_nvidia，现在的 use_gpu 改成 use_cuda，这样跟 use_iluvatar 对得上。

以及相应应该把 nvidia_gpu 包名全改成 cuda，不过改包名我合了再改吧，不然影响的文件太多 pr 不好看了。

2024-12-31 02:56 UTC, YdrMaster commented
另外 xmake 文件模板分成 nv 的一个，iluvatar 的一个吧，直接做两个文件

2024-12-31 03:06 UTC, onenewcode commented
好的

2024-12-31 10:24 UTC, YdrMaster requested changes

2024-12-31 10:24 UTC, YdrMaster commented on operators/src/handle/nvidia_gpu/cxx/nv.lua
> +target_end()
结尾差个换行

2024-12-31 10:24 UTC, YdrMaster commented on operators/src/attention/nvidia_gpu.rs
> +            let compute_ctx = ctx.stream();
这个可以叫 rt（runtime），compute_ctx 有点奇怪。而且我看改法不一致？有的地方是这样造个额外变量，有的地方是用的地方加条件。尽量改一致了，比如说都建变量或者只使用一次的都不建变量之类的

2025-01-02 00:08 UTC, onenewcode commented on operators/src/attention/nvidia_gpu.rs
> +            let compute_ctx = ctx.stream();
已修改为全部新建变量的方式

2025-01-02 00:21 UTC, onenewcode commented on operators/src/handle/nvidia_gpu/cxx/nv.lua
> +target_end()
已添加

2025-01-02 01:56 UTC, YdrMaster approved these changes

2025-01-02 01:56 UTC, merged